name: Sync to Account B

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Account A repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Account B
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git remote add upstream https://x-access-token:${{ secrets.UPSTREAM_TOKEN }}@github.com/mahdibinferdaus/personal_portfolio.git

          git push upstream main --force
